version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - data-pipeline-net
    restart: always

volumes:
  mongo_data:
    driver: local

networks:
  data-pipeline-net:
    external: true
